// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var ExpressServer = require("../src/ExpressServer.bs.js");
var ExpressHandler = require("../src/ExpressHandler.bs.js");
var ExpressHandlerChain = require("../src/ExpressHandlerChain.bs.js");
var ExpressParseJsonHandlerConverter = require("../src/ExpressParseJsonHandlerConverter.bs.js");
var ExpressAuthSessionHandlerConverter = require("../src/ExpressAuthSessionHandlerConverter.bs.js");

var users = [{
    id: 1,
    login: "admin",
    pass: "111"
  }];

function produceAuthData(user) {
  return {
          login: user.login
        };
}

function checkAuthData(userCheckAuthData) {
  return Belt_Array.reduce(users, undefined, (function (curUsr, usr) {
                if (usr.login === userCheckAuthData.login) {
                  return usr;
                } else {
                  return curUsr;
                }
              }));
}

function checkLoginData(loginData) {
  return Belt_Array.reduce(users, undefined, (function (curUsr, usr) {
                if (usr.login === loginData.login && usr.pass === loginData.pass) {
                  return usr;
                } else {
                  return curUsr;
                }
              }));
}

function invalidLoginDataMsg(param) {
  return "Invalid login or password";
}

var UserManager = {
  produceAuthData: produceAuthData,
  checkAuthData: checkAuthData,
  checkLoginData: checkLoginData,
  invalidLoginDataMsg: invalidLoginDataMsg
};

var DefaultHandler = ExpressHandler.MakeDefault(ExpressHandler.DefaultErrorStrategy);

var JsonConverter = ExpressParseJsonHandlerConverter.Make(DefaultHandler);

var JsonHandler = ExpressHandlerChain.Make(DefaultHandler, JsonConverter);

var AuthSessionConverter = ExpressAuthSessionHandlerConverter.Make(JsonHandler, UserManager, ExpressAuthSessionHandlerConverter.DefaultConfigurator);

var AuthSessionHandler = ExpressHandlerChain.Make(JsonHandler, AuthSessionConverter);

var loginPageHtml = "\r\n<form action=\"/apply-login\" method=\"post\">\r\n    <h1>Test form</h1>\r\n    <input name=\"login\" value=\"\" style=\"display: block;\">\r\n    <input name=\"pass\" value=\"\" style=\"display: block;\">\r\n    <input type=\"submit\" style=\"display: block;\">\r\n</form>";

function indexPageHtml(usr) {
  return "\r\nUser: " + usr.login + "<br>\r\n<button onclick=\"window.location.href='/logout'\">Log out</button>";
}

var routes = [
  /* Route */{
    _0: "get",
    _1: "/",
    _2: Curry._1(AuthSessionHandler.handler, (function (r) {
            var maybeUsr = r._1;
            if (maybeUsr !== undefined) {
              return /* AuthSessRes */{
                      _0: {
                        TAG: /* Html */0,
                        _0: indexPageHtml(maybeUsr)
                      },
                      _1: []
                    };
            } else {
              return /* AuthSessRes */{
                      _0: {
                        TAG: /* Redirect */4,
                        _0: "/login",
                        _1: 302
                      },
                      _1: []
                    };
            }
          }))
  },
  /* Route */{
    _0: "get",
    _1: "/login",
    _2: Curry._1(AuthSessionHandler.handler, (function (r) {
            if (r._1 !== undefined) {
              return /* AuthSessRes */{
                      _0: {
                        TAG: /* Redirect */4,
                        _0: "/",
                        _1: 302
                      },
                      _1: []
                    };
            } else {
              return /* AuthSessRes */{
                      _0: {
                        TAG: /* Html */0,
                        _0: loginPageHtml
                      },
                      _1: []
                    };
            }
          }))
  },
  /* Route */{
    _0: "post",
    _1: "/apply-login",
    _2: Curry._1(AuthSessionHandler.handler, (function (r) {
            var extractLoginDataFromJsonData = (function (u) {
            console.log("Json data:" , u);
            if(!u) return undefined;
            if((!u.login) 
                || (typeof u.login !== 'string') 
                || (!u.pass)
                || (typeof u.pass !== 'string')
            ) {
                console.log("no login or pass");
                return undefined;
            }
            return {
                login: u.login,
                pass: u.pass
            };
        });
            var eld = extractLoginDataFromJsonData(r._0._1);
            if (eld !== undefined) {
              var usr = checkLoginData(eld);
              if (usr !== undefined) {
                console.log("Successfull checking login data");
                return /* AuthSessRes */{
                        _0: {
                          TAG: /* Redirect */4,
                          _0: "/",
                          _1: 302
                        },
                        _1: [/* Login */{
                            _0: usr
                          }]
                      };
              } else {
                console.log("Wrong checking login data");
                return /* AuthSessRes */{
                        _0: {
                          TAG: /* Redirect */4,
                          _0: "/",
                          _1: 302
                        },
                        _1: [/* Logout */0]
                      };
              }
            }
            console.log("No loging pata after extraction");
            return /* AuthSessRes */{
                    _0: {
                      TAG: /* Redirect */4,
                      _0: "/",
                      _1: 302
                    },
                    _1: [/* Logout */0]
                  };
          }))
  },
  /* Route */{
    _0: "get",
    _1: "/logout",
    _2: Curry._1(AuthSessionHandler.handler, (function (param) {
            return /* AuthSessRes */{
                    _0: {
                      TAG: /* Redirect */4,
                      _0: "/login",
                      _1: 302
                    },
                    _1: [/* Logout */0]
                  };
          }))
  }
];

ExpressServer.runServer(routes, [], 80, (function (param) {
        console.log("Server started!");
      }));

exports.UserManager = UserManager;
exports.DefaultHandler = DefaultHandler;
exports.JsonConverter = JsonConverter;
exports.JsonHandler = JsonHandler;
exports.AuthSessionConverter = AuthSessionConverter;
exports.AuthSessionHandler = AuthSessionHandler;
exports.loginPageHtml = loginPageHtml;
exports.indexPageHtml = indexPageHtml;
exports.routes = routes;
/* DefaultHandler Not a pure module */
