// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var ExpressServer = require("../src/ExpressServer.bs.js");
var ExpressDefaultLogger = require("../src/ExpressDefaultLogger.bs.js");

var ExpressServerTest = ExpressServer.ExpressServerFactory(ExpressDefaultLogger.ExpressDefaultLogger);

var indexHandler = (function(req, res) {
        res.send("Hello world");
    });

function onInit(param) {
  console.log("Server works");
}

Curry._1(ExpressServerTest.run, {
      handlers: [{
          path: "/",
          routeType: "get",
          middlewares: [],
          handler: indexHandler
        }],
      appMwInits: [],
      port: 80,
      onInit: onInit
    });

exports.ExpressServerTest = ExpressServerTest;
exports.indexHandler = indexHandler;
exports.onInit = onInit;
/* ExpressServerTest Not a pure module */
