// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var ExpressNewServer = require("../src/ExpressNewServer.bs.js");

var routes = [/* Route */{
    _0: "get",
    _1: "/",
    _2: /* Handler */{
      _0: [],
      _1: (function (param, res) {
          var sayHello = (function(res) {
            res.send("Hello world!");
        });
          sayHello(res);
        })
    }
  }];

ExpressNewServer.runServer(routes, [], 80, (function (param) {
        console.log("Server started!");
      }));

exports.routes = routes;
/*  Not a pure module */
