// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var ExpressLoggerStub = require("../stubs/ExpressLoggerStub.bs.js");
var ExpressControllerStub = require("../stubs/ExpressControllerStub.bs.js");
var ExpressServerTemplate = require("../src/ExpressServerTemplate.bs.js");
var ExpressRequestResponseManagerStub = require("../stubs/ExpressRequestResponseManagerStub.bs.js");

var ExpressServerTemplateTest = ExpressServerTemplate.ExpressServerTemplate(ExpressLoggerStub.ExpressLoggerStub, ExpressControllerStub.ExpressControllerStub, ExpressRequestResponseManagerStub.ExpressRequestResponseManagerStub);

var e = Curry._1(ExpressServerTemplateTest.run, 80);

if (e.TAG !== /* Ok */0) {
  ExpressLoggerStub.ExpressLoggerStub.log(ExpressLoggerStub.ExpressLoggerStub.err, e._0);
}

exports.ExpressServerTemplateTest = ExpressServerTemplateTest;
/* ExpressServerTemplateTest Not a pure module */
