// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var ExpressServerTemplate = require("../src/ExpressServerTemplate.bs.js");

var testFilePath = (require('path').resolve(module.path, '..', '..', '..', '..', 'resources', 'test-file.txt'));

var indexPageHtml = "\r\n<form action=\"/apply-post\" method=\"post\">\r\n    <h1>Test form</h1>\r\n    <input name=\"textInp\" value=\"\" style=\"display: block;\">\r\n    <textarea name=\"textAr\" style=\"display: block;\"></textarea>\r\n    <input type=\"submit\" style=\"display: block;\">\r\n</form>\r\n<div>\r\n    <button type=\"button\" onclick=\"window.open('/download-file');\">download file</button>\r\n    <button type=\"button\" onclick=\"window.open('/set-session');\">set session</button>\r\n    <button type=\"button\" onclick=\"window.open('/delete-session');\">delete session</button>\r\n</div>\r\n";

var parseUnknownAsString = (function(val) {
    return (val && (typeof val === 'string'))
        ? val
        : null;
});

var parseUnknownObjectProperty = (function(obj, prop, parser) {
    return (obj[prop]) ? parser(obj[prop]) : null;
});

var routes = [
  /* Route */{
    _0: "get",
    _1: "/",
    _2: {
      TAG: /* Default */1,
      _0: (function (param) {
          return {
                  TAG: /* OnlyResponse */0,
                  _0: {
                    TAG: /* Html */0,
                    _0: indexPageHtml
                  }
                };
        })
    }
  },
  /* Route */{
    _0: "post",
    _1: "/apply-post",
    _2: {
      TAG: /* Default */1,
      _0: (function (req) {
          var reqVals_textInp = parseUnknownObjectProperty(req.bodyData, "textInp", parseUnknownAsString);
          var reqVals_textAr = parseUnknownObjectProperty(req.bodyData, "textAr", parseUnknownAsString);
          var reqVals = {
            textInp: reqVals_textInp,
            textAr: reqVals_textAr
          };
          var result = JSON.stringify(reqVals);
          if (result !== undefined) {
            return {
                    TAG: /* OnlyResponse */0,
                    _0: {
                      TAG: /* Json */1,
                      _0: result
                    }
                  };
          } else {
            return {
                    TAG: /* OnlyResponse */0,
                    _0: {
                      TAG: /* Json */1,
                      _0: "{}"
                    }
                  };
          }
        })
    }
  },
  /* Route */{
    _0: "get",
    _1: "/download-file",
    _2: {
      TAG: /* Default */1,
      _0: (function (param) {
          return {
                  TAG: /* OnlyResponse */0,
                  _0: {
                    TAG: /* DownloadFile */3,
                    _0: testFilePath
                  }
                };
        })
    }
  },
  /* Route */{
    _0: "get",
    _1: "/show-session",
    _2: {
      TAG: /* Default */1,
      _0: (function (req) {
          var sessionVal = parseUnknownObjectProperty(req.session, "sessionVal", parseUnknownAsString);
          var printVal = sessionVal !== undefined ? sessionVal : "";
          return {
                  TAG: /* OnlyResponse */0,
                  _0: {
                    TAG: /* Html */0,
                    _0: "Session-val: " + printVal
                  }
                };
        })
    }
  },
  /* Route */{
    _0: "get",
    _1: "/set-session",
    _2: {
      TAG: /* Default */1,
      _0: (function (param) {
          return {
                  TAG: /* ResponseWithEffects */1,
                  _0: {
                    TAG: /* Redirect */4,
                    _0: "/show-session",
                    _1: 303
                  },
                  _1: [{
                      TAG: /* RequestEffect */0,
                      _0: /* SetSessionVal */{
                        _0: "sessionVal",
                        _1: "11"
                      }
                    }]
                };
        })
    }
  },
  /* Route */{
    _0: "get",
    _1: "/delete-session",
    _2: {
      TAG: /* Default */1,
      _0: (function (param) {
          return {
                  TAG: /* ResponseWithEffects */1,
                  _0: {
                    TAG: /* Redirect */4,
                    _0: "/show-session",
                    _1: 303
                  },
                  _1: [{
                      TAG: /* RequestEffect */0,
                      _0: /* DestroySession */0
                    }]
                };
        })
    }
  }
];

var serverConfig = Curry._3(ExpressServerTemplate.ExpressServerConfiguratorTemplate.buildConfig, routes, 80, (function (param) {
        console.log("Server had been started");
      }));

Curry._1(ExpressServerTemplate.ExpressServerTemplate.run, serverConfig);

exports.testFilePath = testFilePath;
exports.indexPageHtml = indexPageHtml;
exports.parseUnknownAsString = parseUnknownAsString;
exports.parseUnknownObjectProperty = parseUnknownObjectProperty;
exports.routes = routes;
exports.serverConfig = serverConfig;
/* testFilePath Not a pure module */
