// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var SimpleLogger = require("../src/SimpleLogger.bs.js");
var ExpressServer = require("../src/ExpressServer.bs.js");
var ExpressDefaultServerConfigurator = require("../src/ExpressDefaultServerConfigurator.bs.js");

var ExpressDefaultServerConfigurator$1 = ExpressDefaultServerConfigurator.ExpressDefaultServerConfiguratorFactory(SimpleLogger.SimpleLogger);

var routes = [[
    "get",
    "/",
    {
      TAG: /* Default */1,
      _0: (function (param) {
          return {
                  TAG: /* OnlyResponse */0,
                  _0: {
                    TAG: /* Html */0,
                    _0: "<h1>Hello world!</h1>"
                  }
                };
        })
    }
  ]];

var serverConfig = Curry._3(ExpressDefaultServerConfigurator$1.buildConfig, routes, 80, (function (param) {
        console.log("Server had been started");
      }));

var ExpressServerTest2 = ExpressServer.ExpressServerFactory(SimpleLogger.SimpleLogger);

Curry._1(ExpressServerTest2.run, serverConfig);

exports.ExpressDefaultServerConfigurator = ExpressDefaultServerConfigurator$1;
exports.routes = routes;
exports.serverConfig = serverConfig;
exports.ExpressServerTest2 = ExpressServerTest2;
/* ExpressDefaultServerConfigurator Not a pure module */
