// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");

const express = require("express");
;

function Make(OldHandler) {
  var wrapStepReq = function (oldReq) {
    var match = Curry._1(OldHandler.primalReq, oldReq);
    var parse = (function(req) {
      return req.query ? req.query : {};
    });
    return /* UrlReq */{
            _0: oldReq,
            _1: parse(match[0])
          };
  };
  var applyStepRes = function (param, newRes) {
    return newRes;
  };
  var getOldReq = function (newReq) {
    return newReq._0;
  };
  var middlewares = [(express.urlencoded({ extended: true }))];
  return {
          wrapStepReq: wrapStepReq,
          getOldReq: getOldReq,
          applyStepRes: applyStepRes,
          middlewares: middlewares
        };
}

exports.Make = Make;
/*  Not a pure module */
