// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function ExpressControllerStub(Logger) {
  var getHandlerType = function (a) {
    return a.t;
  };
  var getHandlerFunction = function (a) {
    return a.func;
  };
  var getPath = function (a) {
    return a.path;
  };
  var initExpressApp = function (u) {
    return {
            TAG: /* Ok */0,
            _0: undefined
          };
  };
  var getMiddlewares = function (action) {
    return [];
  };
  var defaultHandlerFunc = (function(req, res) {
            res.send("Hello world!")
        });
  var getAllActions = function (param) {
    return [{
              t: /* Get */0,
              path: "/",
              func: defaultHandlerFunc
            }];
  };
  return {
          getAllActions: getAllActions,
          getHandlerType: getHandlerType,
          getHandlerFunction: getHandlerFunction,
          getPath: getPath,
          initExpressApp: initExpressApp,
          getMiddlewares: getMiddlewares
        };
}

exports.ExpressControllerStub = ExpressControllerStub;
/* No side effect */
