// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function getHandlerType(a) {
  return a.t;
}

function getHandlerFunction(a) {
  return a.func;
}

function getPath(a) {
  return a.path;
}

function initExpressApp(u) {
  return {
          TAG: /* Ok */0,
          _0: undefined
        };
}

function getMiddlewares(action) {
  return [];
}

var defaultHandlerFunc = (function(req, res) {
            res.send("Hello world!")
        });

function getAllActions(param) {
  return [{
            t: /* Get */0,
            path: "/",
            func: defaultHandlerFunc
          }];
}

var ExpressControllerStub = {
  getAllActions: getAllActions,
  getHandlerType: getHandlerType,
  getHandlerFunction: getHandlerFunction,
  getPath: getPath,
  initExpressApp: initExpressApp,
  getMiddlewares: getMiddlewares
};

exports.ExpressControllerStub = ExpressControllerStub;
/* No side effect */
