// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function log(lev, err) {
  console.log(err);
}

function initExpressApp(u) {
  return {
          TAG: /* Ok */0,
          _0: undefined
        };
}

function wrap(obj) {
  var msg = obj.message;
  if (msg !== undefined) {
    return msg;
  } else {
    return "";
  }
}

var ExpressLoggerStub = {
  log: log,
  initExpressApp: initExpressApp,
  wrap: wrap,
  err: "error"
};

exports.ExpressLoggerStub = ExpressLoggerStub;
/* No side effect */
