// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function initExpressApp(app) {
  return {
          TAG: /* Ok */0,
          _0: undefined
        };
}

function buildMultipartDataMiddleware(fields) {
  return [];
}

var ExpressRequestResponseManagerStub = {
  initExpressApp: initExpressApp,
  buildMultipartDataMiddleware: buildMultipartDataMiddleware
};

exports.ExpressRequestResponseManagerStub = ExpressRequestResponseManagerStub;
/* No side effect */
