// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");

function Make(OldHandler, Converter) {
  var wrapReq = function (r) {
    return Curry._1(Converter.wrapStepReq, Curry._1(OldHandler.wrapReq, r));
  };
  var applyRes = function (req, res) {
    Curry._2(OldHandler.applyRes, Curry._1(Converter.getOldReq, req), Curry._1(Converter.applyStepRes, res));
  };
  var convert = function (handler, req, res) {
    applyRes(Curry._1(Converter.wrapStepReq, Curry._1(OldHandler.wrapReq, [
                  req,
                  res
                ])), Curry._1(handler, Curry._1(Converter.wrapStepReq, Curry._1(OldHandler.wrapReq, [
                      req,
                      res
                    ]))));
  };
  var primalReq = function (hReq) {
    return Curry._1(OldHandler.primalReq, Curry._1(Converter.getOldReq, hReq));
  };
  var middlewares = Belt_Array.concat(OldHandler.middlewares, Converter.middlewares);
  var handler = function (h) {
    return /* Handler */{
            _0: middlewares,
            _1: (function (param, param$1) {
                return convert(h, param, param$1);
              })
          };
  };
  return {
          wrapReq: wrapReq,
          applyRes: applyRes,
          primalReq: primalReq,
          convert: convert,
          middlewares: middlewares,
          handler: handler
        };
}

exports.Make = Make;
/* No side effect */
