// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");

const express = require("express")
const app = express();
;

var appUnit = app;

function ExpressServerFactory(Logger) {
  var run = function (serverStartConfig) {
    Curry._1(Logger.mapResultError, Curry._1(Logger.catchUnknown, (function (param) {
                Belt_Array.forEach(serverStartConfig.appMwInits, (function (a) {
                        Curry._1(a, appUnit);
                      }));
                Belt_Array.forEach(serverStartConfig.handlers, (function (h) {
                        var regF = (function(route, path, middlewares, handler) {
                        const funParams = [path]
                            .concat(middlewares)
                            .concat([handler]);
                        app[route](...funParams);
                    });
                        regF(h.routeType, h.path, h.middlewares, h.handler);
                      }));
                var start = (function(port, onInit) {
                        app.listen(port, onInit)
                    });
                start(serverStartConfig.port, serverStartConfig.onInit);
              })));
  };
  return {
          run: run
        };
}

exports.appUnit = appUnit;
exports.ExpressServerFactory = ExpressServerFactory;
/*  Not a pure module */
