// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var ExpressServer = require("./ExpressServer.bs.js");
var ExpressDefaultLogger = require("./ExpressDefaultLogger.bs.js");
var ExpressDefaultRequestManager = require("./ExpressDefaultRequestManager.bs.js");
var ExpressDefaultResponseManager = require("./ExpressDefaultResponseManager.bs.js");
var ExpressDefaultServerConfigurator = require("./ExpressDefaultServerConfigurator.bs.js");

var ExpressResponseManagerTemplate = ExpressDefaultResponseManager.ExpressDefaultResponseManagerFactory(ExpressDefaultLogger.ExpressDefaultLogger);

var ExpressRequestManagerTemplate = ExpressDefaultRequestManager.ExpressDefaultRequestManagerFactory(ExpressDefaultLogger.ExpressDefaultLogger);

var ExpressServerConfiguratorTemplate = ExpressDefaultServerConfigurator.ExpressDefaultServerConfiguratorFactory(ExpressDefaultLogger.ExpressDefaultLogger, ExpressResponseManagerTemplate, ExpressRequestManagerTemplate);

var ExpressServerTemplate = ExpressServer.ExpressServerFactory(ExpressDefaultLogger.ExpressDefaultLogger);

exports.ExpressResponseManagerTemplate = ExpressResponseManagerTemplate;
exports.ExpressRequestManagerTemplate = ExpressRequestManagerTemplate;
exports.ExpressServerConfiguratorTemplate = ExpressServerConfiguratorTemplate;
exports.ExpressServerTemplate = ExpressServerTemplate;
/* ExpressResponseManagerTemplate Not a pure module */
