// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");

const express = require("express");
const multer = require("multer");
;

function Make(OldHandler, FileParseConfig) {
  var wrapStepReq = function (oldReq) {
    var match = Curry._1(OldHandler.primalReq, oldReq);
    var parse = (function(req) {
                const files = req.files 
                    ? JSON.parse(JSON.stringify(req.files)) 
                    : {};
                return Object.keys(files).map(k => ({fileName: k, files: files[k]}))
            });
    return /* FileReq */{
            _0: oldReq,
            _1: parse(match[0])
          };
  };
  var getOldReq = function (newReq) {
    return newReq._0;
  };
  var applyStepRes = function (param, newRes) {
    return newRes;
  };
  var produceFileMw = function (param) {
    var mw = (function(fields, dest){
            return multer({ dest: dest }).fields(fields);
        });
    return mw(Curry._1(FileParseConfig.getFileAwaitFields, undefined), Curry._1(FileParseConfig.getDestPath, undefined));
  };
  var middlewares = [produceFileMw(undefined)];
  return {
          wrapStepReq: wrapStepReq,
          getOldReq: getOldReq,
          applyStepRes: applyStepRes,
          middlewares: middlewares
        };
}

exports.Make = Make;
/*  Not a pure module */
